server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yangsheng?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
  data:
    redis:
      host: localhost
      port: 6379
      password: 12345
      database: 0
      timeout: 10000


mybatis-plus:
  type-aliases-package: com.sp.yangshengai.pojo

token:
  secret: yangshengai
  expiration: 7200000
file:
  #???????
  path: /Users/liyu/Downloads/
  # ?????????
  staticAccessPath: /uploadfile/**
  #??????
  PublicNetworkIp: http://localhost:8080/uploadfile/

