server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123

mybatis-plus:
  type-aliases-package: com.pethospital.pethospital.pojo

file:
  #???????
  path: /Users/liyu/Downloads/
  # ?????????
  staticAccessPath: /uploadfile/**
  #??????
  PublicNetworkIp: http://localhost:8080/uploadfile/

