server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yangsheng?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
  data:
    redis:
      host: localhost
      port: 6379
      password: 12345
      database: 0
      timeout: 10000




mybatis-plus:
  type-aliases-package: com.sp.yangshengai.pojo

token:
  secret: token_yangsheng_ai_management_system_random
  expiration: 7200000
file:
  #???????
  path: /Users/liyu/Downloads/
  # ?????????
  staticAccessPath: /uploadfile/**
  #??????
  PublicNetworkIp: http://localhost:8080/uploadfile/

ai-api:
  key: sk-5d2e2cb19cbe4bb78e292a4d4b3aaa6f
  model: deepseek-r1-distill-llama-70b

springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
   # 自定义路径，默认为"/swagger-ui/index.html"
    # Packages to include,多个用 , 分割
  packagesToScan: com.sp.yangshengai.controller


